name: image_to_pdf
description: Convert Images to PDF Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  
  # Image Picker
  image_picker: ^1.0.7
  
  # PDF Generation & Printing/Preview
  pdf: ^3.10.7
  printing: ^5.11.0
  
  # Storage & Path
  path_provider: ^2.1.2
  
  # Fonts & UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  animated_splash_screen: ^1.3.0
  
  # Utilities
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "lib/assets/iconjpg.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/